openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: 'Amazon Import/Export Snowball #X Amz Target=AWSIESnowballJobManagementService.CancelCluster #X Amz Target=AWSIESnowballJobManagementService.CancelCluster #X Amz Target=AWSIESnowballJobManagementService.ListServiceVersions #X Amz Target=AWSIESnowballJobManagementService.ListServiceVersions API'
  description: The Amazon Web Services Snow Family provides a petabyte-scale data transport solution that uses secure devices to transfer large amounts of data between your on-premises data centers and Amazon Simple Storage Service (Amazon S3). The Snow Family commands described here provide access to the same functionality that is available in the Amazon Web Services Snow Family Management Console, which enables you to create and manage jobs for a Snow Family device. To transfer data locally with a Snow Family device, you'll need to use the Snowball Edge client or the Amazon S3 API Interface for Snowball or OpsHub for Snow Family. For more information, see the <a href="https://docs.aws.amazon.com/AWSImportExport/latest/ug/api-reference.html">User Guide</a>.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: snowball
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/snowball-2016-06-30.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://snowball.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Snowball multi-region endpoint
- url: https://snowball.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Snowball multi-region endpoint
- url: http://snowball.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Snowball endpoint for China (Beijing) and China (Ningxia)
- url: https://snowball.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Snowball endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AWSIESnowballJobManagementService.ListServiceVersions'
paths:
  /#X-Amz-Target=AWSIESnowballJobManagementService.ListServiceVersions:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListServiceVersions
      description: Lists all supported versions for Snow on-device services. Returns an array of <code>ServiceVersion</code> object containing the supported versions for a particular service.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListServiceVersionsResult'
              examples:
                ListServiceVersions200Example:
                  summary: Default ListServiceVersions 200
                  x-microcks-default: true
                  value:
                    ServiceVersions: example-value
                    ServiceName: MyResource
                    DependentServices: example-value
                    NextToken: example-value
        '480':
          description: InvalidNextTokenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidNextTokenException'
              examples:
                ListServiceVersions480Example:
                  summary: Default ListServiceVersions 480
                  x-microcks-default: true
                  value: example-value
        '481':
          description: InvalidResourceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidResourceException'
              examples:
                ListServiceVersions481Example:
                  summary: Default ListServiceVersions 481
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListServiceVersionsRequest'
            examples:
              ListServiceVersionsRequestExample:
                summary: Default ListServiceVersions request
                x-microcks-default: true
                value:
                  ServiceName: MyResource
                  DependentServices: example-value
                  MaxResults: example-value
                  NextToken: example-value
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSIESnowballJobManagementService.ListServiceVersions
      summary: Amazon List Service Versions
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AWSIESnowballJobManagementService.ListServiceVersions'
components:
  parameters:
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  schemas:
    ServiceName:
      type: string
      enum:
      - KUBERNETES
      - EKS_ANYWHERE
    ServiceVersionList:
      type: array
      items:
        $ref: '#/components/schemas/ServiceVersion'
    DependentServiceList:
      type: array
      items:
        $ref: '#/components/schemas/DependentService'
    String:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1024
    InvalidResourceException: {}
    ListServiceVersionsRequest:
      type: object
      required:
      - ServiceName
      title: ListServiceVersionsRequest
      properties:
        ServiceName:
          allOf:
          - $ref: '#/components/schemas/ServiceName'
          - description: The name of the service for which you're requesting supported versions.
        DependentServices:
          allOf:
          - $ref: '#/components/schemas/DependentServiceList'
          - description: A list of names and versions of dependant services of the requested service.
        MaxResults:
          allOf:
          - $ref: '#/components/schemas/ListLimit'
          - description: The maximum number of <code>ListServiceVersions</code> objects to return.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: Because HTTP requests are stateless, this is the starting point for the next list of returned <code>ListServiceVersionsRequest</code> versions.
    ListLimit:
      type: integer
      minimum: 0
      maximum: 100
    ListServiceVersionsResult:
      type: object
      required:
      - ServiceVersions
      - ServiceName
      properties:
        ServiceVersions:
          allOf:
          - $ref: '#/components/schemas/ServiceVersionList'
          - description: A list of supported versions.
        ServiceName:
          allOf:
          - $ref: '#/components/schemas/ServiceName'
          - description: The name of the service for which the system provided supported versions.
        DependentServices:
          allOf:
          - $ref: '#/components/schemas/DependentServiceList'
          - description: A list of names and versions of dependant services of the service for which the system provided supported versions.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: Because HTTP requests are stateless, this is the starting point of the next list of returned <code>ListServiceVersionsResult</code> results.
    InvalidNextTokenException: {}
    DependentService:
      type: object
      properties:
        ServiceName:
          allOf:
          - $ref: '#/components/schemas/ServiceName'
          - description: The name of the dependent service.
        ServiceVersion:
          allOf:
          - $ref: '#/components/schemas/ServiceVersion'
          - description: The version of the dependent service.
      description: The name and version of the service dependant on the requested service.
    ServiceVersion:
      type: object
      properties:
        Version:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The version number of the requested service.
      description: The version of the requested service.
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/snowball/
x-hasEquivalentPaths: true
