openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: 'Amazon Import/Export Snowball #X Amz Target=AWSIESnowballJobManagementService.CancelCluster #X Amz Target=AWSIESnowballJobManagementService.CancelCluster #X Amz Target=AWSIESnowballJobManagementService.ListPickupLocations API'
  description: The Amazon Web Services Snow Family provides a petabyte-scale data transport solution that uses secure devices to transfer large amounts of data between your on-premises data centers and Amazon Simple Storage Service (Amazon S3). The Snow Family commands described here provide access to the same functionality that is available in the Amazon Web Services Snow Family Management Console, which enables you to create and manage jobs for a Snow Family device. To transfer data locally with a Snow Family device, you'll need to use the Snowball Edge client or the Amazon S3 API Interface for Snowball or OpsHub for Snow Family. For more information, see the <a href="https://docs.aws.amazon.com/AWSImportExport/latest/ug/api-reference.html">User Guide</a>.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: snowball
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/snowball-2016-06-30.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://snowball.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Snowball multi-region endpoint
- url: https://snowball.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Snowball multi-region endpoint
- url: http://snowball.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Snowball endpoint for China (Beijing) and China (Ningxia)
- url: https://snowball.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Snowball endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AWSIESnowballJobManagementService.ListPickupLocations'
paths:
  /#X-Amz-Target=AWSIESnowballJobManagementService.ListPickupLocations:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListPickupLocations
      description: A list of locations from which the customer can choose to pickup a device.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPickupLocationsResult'
              examples:
                ListPickupLocations200Example:
                  summary: Default ListPickupLocations 200
                  x-microcks-default: true
                  value:
                    Addresses: example-value
                    NextToken: example-value
        '480':
          description: InvalidResourceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidResourceException'
              examples:
                ListPickupLocations480Example:
                  summary: Default ListPickupLocations 480
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListPickupLocationsRequest'
            examples:
              ListPickupLocationsRequestExample:
                summary: Default ListPickupLocations request
                x-microcks-default: true
                value:
                  MaxResults: example-value
                  NextToken: example-value
      parameters:
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSIESnowballJobManagementService.ListPickupLocations
      summary: Amazon List Pickup Locations
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AWSIESnowballJobManagementService.ListPickupLocations'
components:
  schemas:
    ListLimit:
      type: integer
      minimum: 0
      maximum: 100
    Boolean:
      type: boolean
    ListPickupLocationsResult:
      type: object
      example:
        Addresses:
        - AddressId: ADID1234ab12-3eec-4eb3-9be6-9374c10eb51b
          City: Seattle
          Company: My Company
          Country: US
          Name: My Name
          PhoneNumber: 425-555-5555
          PostalCode: '98101'
          StateOrProvince: WA
          Street1: 123 Main Street
      properties:
        Addresses:
          allOf:
          - $ref: '#/components/schemas/AddressList'
          - description: Information about the address of pickup locations.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: HTTP requests are stateless. To identify what object comes "next" in the list of <code>ListPickupLocationsResult</code> objects, you have the option of specifying <code>NextToken</code> as the starting point for your returned list.
    AddressType:
      type: string
      enum:
      - CUST_PICKUP
      - AWS_SHIP
    String:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1024
    Address:
      type: object
      properties:
        AddressId:
          allOf:
          - $ref: '#/components/schemas/AddressId'
          - description: The unique ID for an address.
        Name:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of a person to receive a Snow device at an address.
        Company:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the company to receive a Snow device at an address.
        Street1:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The first line in a street address that a Snow device is to be delivered to.
        Street2:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The second line in a street address that a Snow device is to be delivered to.
        Street3:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The third line in a street address that a Snow device is to be delivered to.
        City:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The city in an address that a Snow device is to be delivered to.
        StateOrProvince:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The state or province in an address that a Snow device is to be delivered to.
        PrefectureOrDistrict:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: This field is no longer used and the value is ignored.
        Landmark:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: This field is no longer used and the value is ignored.
        Country:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The country in an address that a Snow device is to be delivered to.
        PostalCode:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The postal code in an address that a Snow device is to be delivered to.
        PhoneNumber:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The phone number associated with an address that a Snow device is to be delivered to.
        IsRestricted:
          allOf:
          - $ref: '#/components/schemas/Boolean'
          - description: If the address you are creating is a primary address, then set this option to true. This field is not supported in most regions.
        Type:
          allOf:
          - $ref: '#/components/schemas/AddressType'
          - description: Differentiates between delivery address and pickup address in the customer account. Provided at job creation.
      description: The address that you want the Snow device(s) associated with a specific job to be shipped to. Addresses are validated at the time of creation. The address you provide must be located within the serviceable area of your region. Although no individual elements of the <code>Address</code> are required, if the address is invalid or unsupported, then an exception is thrown.
    AddressList:
      type: array
      items:
        $ref: '#/components/schemas/Address'
    ListPickupLocationsRequest:
      type: object
      title: ListPickupLocationsRequest
      properties:
        MaxResults:
          allOf:
          - $ref: '#/components/schemas/ListLimit'
          - description: The maximum number of locations to list per page.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: HTTP requests are stateless. To identify what object comes "next" in the list of <code>ListPickupLocationsRequest</code> objects, you have the option of specifying <code>NextToken</code> as the starting point for your returned list.
    AddressId:
      type: string
      pattern: ADID[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}
      minLength: 40
      maxLength: 40
    InvalidResourceException: {}
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/snowball/
x-hasEquivalentPaths: true
